// GENERATED by scripts/generate-error-content.mjs — do not edit by hand.
// Baked at build time from the Sanity `errorPage` singleton; edits go live on the next deploy.

export const ERROR_PAGE_CONTENT = {
  eyebrow: 'Error',
  headline: 'Something went wrong.',
  message: "Give it another try — or head home and we'll meet you there.",
  retryButtonText: 'Try again',
  homeButtonText: 'Back home',
  homeButtonLink: '/',
} as const
