// GENERATED by scripts/generate-error-content.mjs — do not edit by hand.
// Baked at build time from the Sanity `errorPage` singleton; edits go live on the next deploy.

export const ERROR_PAGE_CONTENT = {
  eyebrow: 'Error',
  headline: 'Something went wrong',
  message: "We're working on it. Please try again in a moment.",
  retryButtonText: 'Try again',
  homeButtonText: 'Go back home',
  homeButtonLink: '/',
} as const
